### ISSUE TITLE
If threads more than 1, there are errors "malformed fastq file"

### ISSUE THREAD

**Issue by juyanmei** [dcdanko/kraken-linked#4]
Hi, Danko.
When I used your test data "tests/data/sample_fastq_zymo_control.fq", and ran code with 4 threads, There are errors as below, but ran code with 1 thread, everything went well. I am wondering why this happens?
> krakenuniq --threads 4 --db refseq --fastq-input sample_fastq_zymo_control.fq --output sample.kraken.out --classified-out sample.class.out --report-file sample.report

Warning: Overwriting sample.report.
kraken-linked/bin/classify -d refseq/database.kdb -i refseq/database.idx -t 4 -f -C sample.class.out -o sample.kraken.out -r sample.report -a refseq/taxDB -p 12 sample_fastq_zymo_control.fq
 Database refseq/database.kdb
Loaded database with 15102006752 keys with k of 31 [val_len 4, key_len 8].
Reading taxonomy index from refseq/taxDB. Done, read 1845140 taxa.
Writing Kraken output to sample.kraken.out
classify: malformed fastq file - quality header (@D00547:847:HYHNTBCXX:2:2208:1571:34089 BX:Z:CTGCGAGGTCTCCCTA-1)
classify: malformed fastq file - sequence header (TAAAAGAGAACCGGGGCCGAAACCCCGGTTGTTATGATTAGCTTGCGACGGC)
classify: malformed fastq file - sequence header (TAAAAGAGAACCGGGGCCGAAACCCCGGTTGTTATGATTAGCTTGCGACGGC

**Comment by dcdanko** [comment]
I've seen some issues running KrakenLinked with multiple threads on certain platforms. It's not ideal but for now the best advice I can give is to run with a single thread.
